blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^(?P<id>[0-9]+)$', views.article, name='article'),
    url(r'^edit/(?P<id>[0-9]+)*$', views.edit, name='edit'),
    url(r'^edit/action/(?P<id>[0-9]+)*$', views.edit_action, name='edit_action'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32, default='title')
    content = models.TextField(null=True)
    createtime = models.DateTimeField(null=True)

    def __unicode__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from . import models


# Create your views here.
def index(request):
    articles = models.Article.objects.all()
    return render(request, 'index.html', {'articles': articles})


def article(request, id):
    article = models.Article.objects.get(pk=id)
    return render(request, 'article.html', {'article': article})


def edit(request, id):
    if id:
        article = models.Article.objects.get(pk=id)
        return render(request, 'edit.html', {'article': article})
    return render(request, 'edit.html')


def edit_action(request, id):
    title = request.POST['title']
    content = request.POST.get('content', 'content')
    if id:
        article = models.Article.objects.get(pk=id)
        article.title = title
        article.content = content
        article.save()
        return HttpResponseRedirect('/blog/%s'%id)
    models.Article.objects.create(title=title, content=content)
    return HttpResponseRedirect('/blog')

blog/templates/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ article.title }}</title>
</head>
<body>
    <h1>{{ article.title }}</h1>
    <p>{{ article.content }}</p>
    <a href="{% url 'blog:edit' article.id %}">修改文章</a>
</body>
</html>

blog/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        form {
            display: flex;
            flex-direction: column;
            width: 500px;
            line-height: 1.6;
        }

        input[type=submit] {
            width: 50px;
        }
    </style>
</head>
<body>
<form action="{% url 'blog:edit_action' article.id %}" method="post">
    {% csrf_token %}
    <label for="title">标题</label>
    <input type="text" name="title" id="title" value="{{ article.title }}">
    <label for="content">内容</label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
    <input type="submit">
</form>
</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ article.title }}</title>
</head>
<body>
<ul>
    {% for article in articles %}
        <li><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a></li>
    {% endfor %}
    <a href="{% url 'blog:edit' %}">增加新文章</a>
</ul>
</body>
</html>